### ISSUE TITLE
dtype and passed std::vector<T> data type may not match

### ISSUE THREAD

**Issue by take-cheeze** [pfnet-research/chainer-compiler#711]
https://github.com/pfnet-research/chainer-compiler/blob/4b17f24c3aff52a22b0ca2fcbcf59ace5de5f2f2/compiler/gradient.cc#L29
https://github.com/pfnet-research/chainer-compiler/blob/4b17f24c3aff52a22b0ca2fcbcf59ace5de5f2f2/compiler/gradient_with_order.cc#L33

**Comment by take-cheeze** [comment]
At least we need check like `CHECK_EQ(type.dtype().SizeOf(), sizeof(T))` near:
https://github.com/pfnet-research/chainer-compiler/blob/189e3d83ccf12b862a43f233fd3788bfdd3946b4/compiler/graph_builder.cc#L96

**Comment by shinh** [comment]
Yeah, these functions are extremely error prone but I didn't improve it at that time since

1. These functions are not often used
2. If we create type-safe variant for them, it will look like ChainerX's ArrayBuilder (https://github.com/chainer/chainer/blob/master/chainerx_cc/chainerx/testing/array.h#L24) and I didn't want dup code.

Now that `Tensor` is internally using ChainerX's array, I guess it makes sense to use chainerx::ArrayBuilder and remove these type-unsafe functions?
